name: CI + Deploy to Render

on:
    pull_request:
    push:
        branches: [task-manager-fsc]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            # Step 1: Pega o código do repositório
            - uses: actions/checkout@v3

            # Step 2: Roda testes
            - name: Run tests
              run: |
                  cd back-end
                  npm install
                  npm test

            # Step 3: Só faz deploy se tiver na branch main e os testes passarem
            - name: Deploy to Render
              if: github.ref == 'refs/heads/task-manager-fsc'
              env:
                  deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
              run: |
                  curl "$deploy_url"
